dir: /scratch/tweber/DATA/MC_DATA/NO_EVA_2106
comparisons:
  # - GM19705x01,GM19705iTRU3C,GM19705
  # - HGSVCxpool1x01,HGSVCPool1x02,HGSVCpool1quadrant2KAPA,HGSVCxPool1
  - BAB3114,BAB3161,BAB14547,KM1096,KM1086x01,RPE1x04,MNaseConcTest